### ISSUE TITLE
languages does not load

### ISSUE THREAD

**Issue by basarik** [faruktoptas/ytranslate-chrome-extension#2]
java script error:
translate.yandex.net/api/v1.5/tr.json/getLangs?ui=en&key=undefined Failed to load resource: the server responded with a status of 403 (Forbidden)
options.html:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at createOptions (options.js:47)
    at XMLHttpRequest.xhr.onreadystatechange (options.js:39)

**Comment by faruktoptas** [comment]
Fixed
